let minecraft_ban_items_1789228019852_server = [
	"minecraft:wooden_sword",
	"minecraft:wooden_shovel",
	"minecraft:wooden_pickaxe",
	"minecraft:wooden_axe",
	"minecraft:wooden_hoe",
	"minecraft:stone_sword",
	"minecraft:stone_shovel",
	"minecraft:stone_pickaxe",
	"minecraft:stone_axe",
	"minecraft:stone_hoe",
	"minecraft:iron_sword",
	"minecraft:iron_shovel",
	"minecraft:iron_pickaxe",
	"minecraft:iron_axe",
	"minecraft:iron_hoe",
	"minecraft:golden_sword",
	"minecraft:golden_shovel",
	"minecraft:golden_pickaxe",
	"minecraft:golden_axe",
	"minecraft:golden_hoe",
	"minecraft:diamond_sword",
	"minecraft:diamond_shovel",
	"minecraft:diamond_pickaxe",
	"minecraft:diamond_axe",
	"minecraft:diamond_hoe",
	"minecraft:netherite_sword",
	"minecraft:netherite_shovel",
	"minecraft:netherite_pickaxe",
	"minecraft:netherite_axe",
	"minecraft:netherite_hoe",
	"minecraft:trident",
	"minecraft:shield",
	"minecraft:bow",
	"minecraft:crossbow",
	"minecraft:crafting_table",
];
let minecraft_ban_wearables_1789228019852_server = [
	"minecraft:leather_helmet",
	"minecraft:chainmail_helmet",
	"minecraft:iron_helmet",
	"minecraft:golden_helmet",
	"minecraft:diamond_helmet",
	"minecraft:netherite_helmet",
	"minecraft:leather_chestplate",
	"minecraft:chainmail_chestplate",
	"minecraft:iron_chestplate",
	"minecraft:golden_chestplate",
	"minecraft:diamond_chestplate",
	"minecraft:netherite_chestplate",
	"minecraft:leather_leggings",
	"minecraft:chainmail_leggings",
	"minecraft:iron_leggings",
	"minecraft:golden_leggings",
	"minecraft:diamond_leggings",
	"minecraft:netherite_leggings",
	"minecraft:leather_boots",
	"minecraft:chainmail_boots",
	"minecraft:iron_boots",
	"minecraft:golden_boots",
	"minecraft:diamond_boots",
	"minecraft:netherite_boots",
	"minecraft:turtle_helmet",
];
ServerEvents.recipes(event => event.remove({ output: minecraft_ban_items_1789228019852_server}));
ServerEvents.recipes(event => event.remove({ output: minecraft_ban_wearables_1789228019852_server}));
ServerEvents.tags("item", event => event.add("c:hidden_from_recipe_viewers", minecraft_ban_items_1789228019852_server));
ServerEvents.tags("item", event => event.add("c:hidden_from_recipe_viewers", minecraft_ban_wearables_1789228019852_server));
