
[milestones]
	#初始拥有的心数。
	#范围：0 ~ 1000
	baseHearts = 10
	#达成新里程碑时获得的心数。
	#范围：0 ~ 1000
	heartsPerMilestone = 1
	#按升序排列的、解锁每个里程碑所需食用的不同食物数量列表。自然，添加更多里程碑可让你获得更多心。
	milestones = [5, 10, 18, 28, 42, 60, 85, 120, 165, 225, 300, 400]

[filtering]
	#此列表中的食物不会影响玩家生命值，也不会出现在食物手册中。
	blacklist = []
	#当此列表包含任何内容时，黑名单将被忽略，只有此处的食物才计入。
	whitelist = []
	#食物要计入里程碑所需提供的最低饥饿值，以半根鸡腿为单位。
	#范围：0 ~ 1000
	minimumFoodValue = 1

[miscellaneous]
	#死亡时是否重置食物列表，即失去所有奖励心。
	resetOnDeath = false
	#若为 true，在生存模式之外（如创造/冒险模式）食用食物不会被记录，因此不计入进度。
	limitProgressionToSurvival = false
