
[Parry]
	#Activates or disables enchantment
	Active = true
	#Chance of blocking an attack 0.15 at default.
	Chance = 0.15

[Evasive]
	#Activates or disables enchantment
	Active = true
	Chance = 0.25

[Agility]
	#Activates or disables enchantment
	Active = true
	#Speed per level of enchantment
	Speed = 0.01
	#Max level of enchantment
	"Max Level" = 2

[Lifesteal]
	#Activates or disables enchantment
	Active = true
	#Percentage of damage healed per level.
	Percentage = 0.1
	#Max level of enchantment
	"Max Level" = 1

["Light Weight"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 3

[Envenomed]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 3

[Vitality]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 5
	#Percentual amount of health per level
	Health = 0.1

[Purge]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 5
	#Chance per level
	Chance = 0.1
	#Base bonus damage when purging a positive effect
	"Base dmg" = 2.5
	#Damage bonus per level of purge
	"Increase dmg" = 2.5

["Ash Destroyer"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 5
	#Percentage of damage per level
	"Damage Increase" = 0.2

[Headless]
	#Activates or disables enchantment
	Active = true

[Viper]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 5
	#Base damage bonus for poisoned enemies, doesnt scale with levels
	"Poisoned base damage" = 2.25
	#Damage bonus per level to poisoned enemies
	"Poisoned bonus damage" = 0.75
	#Base damage bonus for withered enemies, doesnt scale with levels
	"Withered base damage" = 1.5
	#Damage bonus per level to withered enemies
	"Withered bonus damage" = 0.5

["Curse of Possession"]
	#Activates or disables enchantment
	Active = true

["Swifter Slashes"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 5
	#Bonus attack speed per level
	"Attack Speed" = 0.05

["Advanced Swifter Slashes"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 5
	#Bonus base attack speed
	"Attack Speed Base" = 0.25
	#Bonus attack speed per level
	"Attack Speed" = 0.05

["Supreme Swifter Slashes"]
	#Activates or disables enchantment
	Active = true
	#Should enchantment be findable in loot
	Discoverable = false
	#Max level of enchantment
	"Max Level" = 5
	#Bonus base attack speed
	"Attack Speed Base" = 0.5
	#Bonus attack speed per level
	"Attack Speed" = 0.1

["Advanced Looting"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 3

[Adept]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 3
	#Percentual increase in experience per level
	"Percentual increase" = 0.3
	#Percentual increase in experience per level for bossess
	"Percentual boss increase" = 0.15
	#Amount of original XP after the enchantment considers a mob a Boss
	Threshold = 25

["Piercing Capabilities"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4
	#Percentage of damage that ignores reductions per level
	Percentage = 0.25

["Advanced Protection"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4
	#Should enchantment be findable in loot
	Findable = true
	#Activates extra damage reduction before vanilla calculations
	Extra = true

["Advanced Blast Protection"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4
	#Should enchantment be findable in loot
	Findable = false

["Advanced Projectile Protection"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4
	#Should enchantment be findable in loot
	Findable = false

["Advanced Fire Protection"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4
	#Should enchantment be findable in loot
	Findable = false

["Advanced Feather Falling"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4

["Advanced Efficiency"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 5
	#Should enchantment be findable in loot
	Findable = true

["Advanced Lure"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 3

["Advanced Luck of the Sea"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 2

["Advanced Fortune"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 3
	#Should enchantment be findable in loot
	Findable = false

["Advanced Sharpness"]
	#Activates or disables enchantment
	Active = true
	#Increased damage at level 1
	"Base damage" = 4.0
	#Increased damage per level
	"Damage Increase" = 0.5

["Supreme Sharpness"]
	#Activates or disables enchantment
	Active = true
	#Should enchantment be findable in loot
	Findable = false

["Lethal Cadence"]
	#Activates or disables enchantment
	Active = true
	#Chance of ignoring iframes
	Chance = 0.05

[Range]
	#Activates or disables enchantment
	Active = true
	#Multiplier Speed for arrows, below 1 will cause arrows to be slower
	Boost = 1.25

["Advanced Power"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 5

["Arrow Piercing"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4
	#Percentage of damage that ignores reductions per level
	Percentage = 0.25

[Vulnerability]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4
	#Percentage of damage increased per level
	Percentage = 0.08

["Double Edge"]
	#Activates or disables enchantment
	Active = true
	#Percentage of damage dealt increased
	"Damage Bonus" = 0.25
	#Percentage of damage dealt to itself
	"Self Damage" = 0.5

["Heavy Weight"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 5
	#Attack Speed Decrease
	Percentage = 0.2

["Advanced Smite"]
	#Activates or disables enchantment
	Active = true

["Supreme Smite"]
	#Activates or disables enchantment
	Active = true
	#Should enchantment be findable in loot
	Findable = false

["Advanced Bane of Arthropods"]
	#Activates or disables enchantment
	Active = true

["Supreme Bane of Arthropods"]
	#Activates or disables enchantment
	Active = true
	#Should enchantment be findable in loot
	Findable = false

["Armor Piercing"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4
	#Base percentage of damage that ignores armor
	Base = 0.15
	#Percentage of damage that ignores armor per level
	Percentage = 0.15

["Magic Piercing"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4
	#Base percentage of damage that ignores armor
	Base = 0.15
	#Percentage of damage that ignores enchantments per level
	Percentage = 0.15

["Critical Strike"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4
	#Percentage of damage per level
	"Level Damage Increase" = 0.25
	#Base percentage damage
	"Base Damage Increase" = 0.5
	#Percentage chance per level
	"Chance Increase" = 0.05

["Giant Slayer"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4
	#Percentage of damage per level
	"Level Damage Increase" = 0.01
	#Base percentage damage
	"Base Damage Increase" = 0.02
	#Max damage bonus possible
	"Max damage" = 10.0

[Executioner]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4
	#Percentage of missing health as damage per level
	"Level Damage Increase" = 0.1
	#Base Percentage of missing health as damage
	"Base Damage Increase" = 0.1
	#Max damage bonus possible
	"Max damage" = 10.0

[Shielded]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 5
	#Max amount of absorption per level
	Absorption = 2.0

[Heating]
	#Activates or disables enchantment
	Active = true

[Chilling]
	#Activates or disables enchantment
	Active = true

[Butcher]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 3

["Advanced Butcher"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 3

[Learning]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 3
	#Percentual increase in experience per level
	"Percentual increase" = 0.6
	#Amount of original XP after the enchantment considers a mob a Boss
	Threshold = 25

["Double Jump"]
	#Activates or disables enchantment
	Active = true

[Harvester]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4
	#Increase in damage per kill
	"Damage Increase" = 0.06
	#Initial max amount of kills
	"Base kills" = 80
	#Increase in max amount of kills per level
	"Increase per levels" = 30

["Advanced Thorns"]
	#Activates or disables enchantment
	Active = true

["Supreme Thorns"]
	#Activates or disables enchantment
	Active = true

["Burning Thorns"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 3
	#Base duration per tick
	"Base duration" = 20
	#Increase duration in ticks per level
	"Duration per level" = 20
	#Increased thorn damage if target is already on fire
	"Multiplier bonus" = 1.5

["Freezing Thorns"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 3
	#Base duration per tick
	"Base duration" = 20
	#Increase duration in ticks per level
	"Duration per level" = 20
	#Increased thorn damage if target is already freezing
	"Multiplier bonus" = 1.5

[Cleaving]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 3
	#Increased percentage per level
	"Increased percentage" = 0.1
	#Base Percentage of damage
	"Base percentage" = 0.1
	#This activates the tweak, if set to false, the will disable the enchantment in some cases
	"Cleaving Tweak" = true

["Lucky Odds"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 2

["High Jump"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 2

["Advanced Fire Aspect"]
	#Activates or disables enchantment
	Active = true

["Supreme Fire Aspect"]
	#Activates or disables enchantment
	Active = true
	#Should enchantment be findable in loot
	Findable = false

["Cold Aspect"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 2

["Advanced Cold Aspect"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 2

["Supreme Cold Aspect"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 2
	#Should you be able to find this enchantment on naturally generated loot
	Findable = false

["Ice Breaker"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 5
	#Bonus flat damage per level
	"Flat Bonus" = 1.25
	#Amount of extra freezing amount needed to deal even more damage, an integer
	Threshold = 0
	#Percentual bonus damage per level when the freezing point is reached
	"Percentage Bonus" = 0.1

["Natural Blocking"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 2
	#Percentage of damage reduced as base
	"Base reduction" = 0.1
	#Damage reduction per level
	"Reduction per level" = 0.05

[Repairable]
	#Activates or disables enchantment
	Active = true
	#Should you be able to find this enchantment on naturally generated loot
	Findable = false

["Healthy Heart"]
	#Activates or disables enchantment
	Active = true
	#Should you be able to find this enchantment on naturally generated loot
	Findable = true
	#Max level of enchantment
	"Max Level" = 2
	#Base percentage of healing
	"Base increase" = 0.1
	#Percentage of healing increase per level
	"Level increase" = 0.05

["Advanced Razors Edge, only works if Spartan Weaponry is on"]
	#Activates or disables enchantment
	Active = true
	#Should you be able to find this enchantment on naturally generated loot
	Findable = true
	#Max level of enchantment
	"Max Level" = 5

["Supreme Razors Edge, only works if Spartan Weaponry is on"]
	#Activates or disables enchantment
	Active = true
	#Should you be able to find this enchantment on naturally generated loot
	Findable = false
	#Max level of enchantment
	"Max Level" = 5

[Crippling]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 3

[Merciful]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 5
	#Base damage bonus for slowed enemies, doesnt scale with levels
	"Slowed base damage" = 0.75
	#Damage bonus per level to slowed enemies
	"Slowed bonus damage" = 1.25
	#Base damage bonus for weakened enemies, doesnt scale with levels
	"Weakened base damage" = 0.75
	#Damage bonus per level to weakened enemies
	"Weakened bonus damage" = 0.75

["Lava Strider"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 3

["Supreme Protection"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4
	#Should enchantment be findable in loot
	Findable = false

[Durable]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 3

["Brutal Hits"]
	#Activates or disables enchantment
	Active = true
	#Max level of enchantment
	"Max Level" = 4
	#Percentage of durability damage done to armor
	"Armor Damage" = 0.01
	#Multiplier of damage increase when First Aid mod is on
	"FirstAid Multiplier" = 2

