
[Enchantment]
	#是否启用横扫类攻击中仅主目标会触发附魔效果。
	"Enchant Main Target Only" = true
	#是否启用赐福之源附魔。
	"Source of Blessing" = true
	#是否启用诅咒之源附魔。
	"Source of Curses" = true
	#祝福之源触发概率，超过100%的部分会再次判断。(可用变量：EnchantLevel)
	"Source of Blessing Probability" = "EnchantLevel * 0.2"
	#诅咒之源触发概率，超过100%的部分会再次判断。(可用变量：EnchantLevel)
	"Source of Curses Probability" = "EnchantLevel * 0.2"
	#消法之刃是否只消除正面效果。
	"Elimination Positive Only" = true
	#破法附魔消除被攻击者的药水效果的概率，超过100%的部分会再次判断。
	"Elimination Effect Probability" = "EnchantLevel * 0.3"
	#是否启用诅咒之源附魔。
	"Only Eliminate Positive Effects" = true
	#破甲附魔为敌人附加破甲效果的概率。
	"Sunder Armor Probability" = "EnchantLevel * 0.1"
	#剧毒之刃施加剧毒效果的几率。
	"Administer Poison Probability" = "EnchantLevel * 0.15"
	#腐败施加施加腐蚀效果的几率。
	"Infliction Corrosion Probability" = "EnchantLevel * 0.1"
	#抑疗施加弱效恢复效果的几率
	"Inhibit Therapy Probability" = "EnchantLevel * 0.08"

[Effects]
	#是否启用超级腐蚀(可腐蚀无法破坏装备)
	"Supre Corrosion" = false
	#近战领域buff的无敌范围(范围内造成的伤害无效，可用变量：damage，effectLevel，)
	"Melee Domain Distance" = "0.5 * effectLevel"
	#每级闪避提供多少闪避概率。(1%~100%)
	"Evasion Probability" = 4.0
	#每级护甲碎裂减少多少护甲值。
	"Armor Broken" = 4.0
	#每级护甲碎裂减少多少护甲韧性。
	"Armor Toughness Broken" = 1.0
	#每级巨力增加百分之多少的伤害。
	"Huge Force Damage" = 0.25
	#伤害变为：(1-x)^溃力等级-溃力等级。
	"Wane Reduce damage" = 0.2
	#每级脆弱增加多少被造成的伤害。
	"Fragile Damage" = 0.25
	#每级吸血增加百分之多少的吸血量。
	"Leeching Health" = 0.1
	#每级精准增加的伤害。
	"Accurate Damage" = 0.25
	#每级失准减少的伤害。
	"Misalignment Reduce Damage" = 0.2
	#每级弱效回复减少的回复量。
	"Weaking Recovery Reduce Heal Amount" = 0.2
	#使伤害变为：伤害*(实体的损失生命值百分比^x)*效果等级
	"Slaughter Damage" = 0.35
	#受到伤害时额外受到(损失的生命值*x)*效果等级的伤害
	"Injury Accumulation" = 0.08
	#魔力聚焦增加造成的魔法伤害百分比。
	"Magic Focus Damgae" = 0.25
	#魔法护盾减少的受到的魔法伤害的百分比。
	"Magic Shield Reduce Damage" = 0.2
	#魔力抑制减少造成的魔法伤害的百分比。
	"Magic Inhibition Reduce Damage" = 0.3
	#魔法破防增加的受到伤害的百分比
	"Broken Magic Shield Damage" = 0.3
	#每级强心提升恢复的生命值。
	"Strong Heart Recovery" = 0.25
	#0：在得到药水效果时增加时长（增加30+等级*30秒时长）；1：若该buff等级≥其它状态效果数量，则令其它状态效果的持续时间不会降低，直至该buff消失。  若该buff等级＜其它状态效果数量，则令其它状态效果轮流消耗持续时间
	Extension_method = 0.0
	#每级诅咒效果施加几种对应的负面效果。(Range：1-4)
	"Curse Count" = 2.0
	#汲魔效果的基础窃取效果率。
	"Base Steal Chance" = 0.2
	#汲魔效果窃取的效果时长减少比例，原时长*（1-x^效果等级）
	"Duration Ratio" = 0.5
	#汲魔效果的是否只窃取正面效果。
	"Only Steal Postive Effect" = true
	#[黑名单]不会被汲魔效果窃取到的效果。（白名单为空时生效）
	"Stolen Effect Exclusion" = []
	#[白名单]能被汲魔效果窃取到的效果。
	"Stolen Effect Selected" = []
	#[黑名单]不会被随机效果抽取到的效果。（白名单为空时生效）
	"Random Effect Exclusion" = []
	#[白名单]能被随机效果抽取到的效果。
	"Random Effect Selected" = []
	#每级混乱增加的阻力（0.2+x*level）
	"Resistance Per Level" = 0.3
	#混乱buff的基础随机位移。
	"Base Randomness" = 0.2
	#每级混乱增加的随机位移。
	"Randomness Per Level" = 0.15
	#每级混乱减少的视角扰动间隔，单位为tick（15-x*level）
	"Rotation Interval Reduction Per Level" = 4.0
	#不会被升级效果提升等级的效果。
	"Upgrade Exclusion" = []
	"Super Death Mode" = false
	#不屈触发的概率。（可用的变量：effectLevel）
	"Unyielding Chance" = "1 - 0.8^effectLevel"
	#每级生命转化的转化率
	"Health Conversion Ratio" = 0.2
	#赌徒效果是否显示提示文本。
	"Gambler Show Text" = true
	#盛宴效果增强后食物提供的饱食度/饱和度增幅。（可用变量effectLevel）
	"Feast Food Enhanced" = "1 + 0.5 * effectLevel"
	#药水拮抗效果是否影响负面效果。
	"Negative Potion Antagonism" = false
	#药水拮抗效果对新获得的效果削减的持续时间。（可用变量:effectLevel、duration）
	"Potion Antagonism Reduce" = "duration * 0.5 ^ effectLevel"
	#动能效果的增伤公式，速度单位为(m/tick)。（可用变量:effectLevel、damage、speed）
	"Kinetic Calculation Formula" = "damage * speed * effectLevel * 0.25 + effectLevel * speed * 2"
	#当玩家有多少个正面效果时会获得副作用效果。（设置0以禁用）
	"Side Effect Limit" = 0.0
	#有副作用效果时每次获得新正面效果产生几个负面效果。(可用变量：SideEffectLevel、NewEffectLevel)
	"Number of Side Effects" = "SideEffectLevel"
	#[白名单]同伴效果触发时施加给玩家的随机效果的列表（留空为完全随机）。
	"Companion Effects List" = []
	#破碎的心效果减少的最大生命值百分比（可用变量：maxHealth、effectLevel）。
	"Shattered Heart Reduced Health" = "maxHealth*0.1*effectLevel"
	#生命链接的承伤半径（可用变量：effectLevel）
	"Injury Link Radius" = "3 + effectLevel"
	#是否启用位格效果的粒子。
	"Enable Rank Particle" = true
	#[白名单]能被复用效果回收的效果
	"Reuse Effect Exclusion" = []
	#[黑名单]能被汲魔效果窃取到的效果。（白名单为空时生效）
	"Reuse Effect Selected" = []

[EntitySpawn]
	#生成的生物带有位格效果的最大等级，设为0以禁用。
	"Max Rank Level" = 0.0
	#最大位格权重，每个有位格效果的生物占3^效果等级的权重。
	"Max Rank Exist" = 300.0
	#生成时不会获得位格的生物。
	"No Rank Entity" = []
	#位格生物生成时是否带有额外效果。
	"Rank Effect" = true
	#是否给周围同种生物添加弱化的增幅效果。
	"Enhance the followers" = true
	#生成时带有位格的生物。eg.'1->minecraft:zombie,minecraft:skeleton','2->minecraft:creeper,minecraft:spider','3->minecraft:ender_dragon'
	"Rank Entity" = []
	#生成时生物带有位格的概率。eg'1:0.1',   // 10% 概率生成1级位格     '2:0.05',  // 5% 概率生成2级位格     '3:0.01',  // 1% 概率生成3级位格     '4:0.001', // 0.1% 概率生成4级位格
	"Rank Spawn Possibility" = []

[Special]
	#禁用的药水效果
	"Ban List" = []
	#能被强行添加到生物的效果。
	"Force effects" = []
	#强行使列表中的生物能被添加药水效果。
	"Entity list" = []
	#不会被移除的药水效果，除了持续时间结束或/force_effect
	"NON-Removable Effects" = []

[Immune]
	#免疫效果所能免疫的效果
	"Immune Effects" = ["more_potion_effects:virus, minecraft:unluck, minecraft:hunger, minecraft:slowness, minecraft:blindness, minecraft:poison, minecraft:nausea", "minecraft:wither, minecraft:mining_fatigue, minecraft:weakness, minecraft:darkness, more_potion_effects:highly_toxic, more_potion_effects:injury_accumulation, more_potion_effects:fear, more_potion_effects:combustion, more_potion_effects:spatial_anchor, more_potion_effects:slot_lock", "more_potion_effects:corrosion, more_potion_effects:wane, more_potion_effects:armor_broken, more_potion_effects:broken_magic_shield, more_potion_effects:magic_inhibition, more_potion_effects:weakening_recovery, more_potion_effects:bleeding, more_potion_effects:aggro, more_potion_effects:deflagration", "more_potion_effects:dispel, more_potion_effects:injury_outburst, more_potion_effects:potion_antagonism, more_potion_effects:death"]

