#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Sep 14 19:46:15 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=
enableShaders=false
