#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Sep 30 01:07:44 CST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.9.3.zip
enableShaders=false
