let iceandfire_ban_items_1789293812744 = [
	"iceandfire:dragonbone_sword",
	"iceandfire:dragonbone_axe",
	"iceandfire:dragonbone_pickaxe",
	"iceandfire:dragonbone_shovel",
	"iceandfire:dragonbone_hoe",
	"iceandfire:silver_sword",
	"iceandfire:silver_axe",
	"iceandfire:silver_pickaxe",
	"iceandfire:silver_shovel",
	"iceandfire:silver_hoe",
	"iceandfire:copper_sword",
	"iceandfire:copper_axe",
	"iceandfire:copper_pickaxe",
	"iceandfire:copper_shovel",
	"iceandfire:copper_hoe",
	"iceandfire:myrmex_desert_sword_venom",
	"iceandfire:myrmex_jungle_sword_venom",
	"iceandfire:myrmex_desert_sword",
	"iceandfire:myrmex_jungle_sword",
	"iceandfire:myrmex_desert_axe",
	"iceandfire:myrmex_jungle_axe",
	"iceandfire:myrmex_desert_pickaxe",
	"iceandfire:myrmex_jungle_pickaxe",
	"iceandfire:myrmex_desert_shovel",
	"iceandfire:myrmex_jungle_shovel",
	"iceandfire:myrmex_desert_hoe",
	"iceandfire:myrmex_jungle_hoe",
	"iceandfire:dread_sword",
	"iceandfire:dread_knight_sword",
	"iceandfire:dread_queen_sword",
	"iceandfire:tide_trident_inventory",
];
let iceandfire_ban_wearables_1789293812744 = [
];
ItemEvents.tooltip(event => event.add(iceandfire_ban_items_1789293812744, Text.red("此物品无法使用")));
ItemEvents.tooltip(event => event.add(iceandfire_ban_wearables_1789293812744, Text.red("此物品无法使用")));
